GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY5NDI4ODgxOSwiZXhwIjoxNjk0Mjg4ODM0fQ.6OwpYJJfGvKYrKlibEmGFGEJMv3tfNLI3kVBhOazQtA

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Kyle"
}

###

DELETE http://localhost:3000/logout