GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY5NDMyMzk5OCwiZXhwIjoxNjk0MzI0MDEzfQ.7mOBaglz0q66pKwSP4_t5awu4ez6uAt4vttLMLT6Yp4

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY5NDMyMzkwMn0.PJa12Y25TVfxXE7CyNFPJoCthGp3wnUVbJ6tVM0HnY0"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY5NDMyMzkwMn0.PJa12Y25TVfxXE7CyNFPJoCthGp3wnUVbJ6tVM0HnY0"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Kyle"
}
